version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: MYSQL_DATABASE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud
      MYSQL_USER: user_crud
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306" 
    